# Tyler Yamashiro
# Makefile

p4:	numMixer.cpp seer.cpp tmSeer.cpp volatileSeer.cpp numMixerSeer.cpp numMixerTmSeer.cpp numMixerVolatileSeer.cpp p4.cpp
	g++ -Wall -Werror -pedantic -std=c++11 numMixer.cpp seer.cpp tmSeer.cpp volatileSeer.cpp numMixerSeer.cpp numMixerTmSeer.cpp numMixerVolatileSeer.cpp p4.cpp -o p4
	